--- 
document:
  name: Elenco basi di dati chiave
  description: |
    Questo documento rappresenta il risultato dell’azione “Individuazione
    delle basi di dati chiave” definita nell’ambito degli Open Data del Piano
    Triennale per l’Informatica nella PA (2017-2019).
  tags:
    - pianotriennale
